export default function () {
  return [
    { title: "JavaScript: The Good Parts", pages: 172, author: "Douglas Crockford", cover: "https://covers.oreillystatic.com/images/9780596517748/lrg.jpg", genre: "Educational", published: "2008", summary: "Most programming languages contain good and bad parts, but JavaScript has more than its share of the bad, having been developed and released in a hurry before it could be refined. This authoritative book scrapes away these bad features to reveal a subset of JavaScript that's more reliable, readable, and maintainable than the language as a whole-a subset you can use to create truly extensible and efficient code."},
    { title: "Harry Potter and the Sorcerer's Stone", pages: 309, author: "J.K. Rowling", cover: "https://upload.wikimedia.org/wikipedia/en/b/bf/Harry_Potter_and_the_Sorcerer%27s_Stone.jpg", genre: "Fantasy", published: "1997", summary: "Harry Potter learns on his eleventh birthday that he is the orphaned son of two powerful wizards and possesses unique magical powers of his own. He is summoned from his life as an unwanted child to become a student at Hogwarts, an English boarding school for wizards. There, he meets several friends who become his closest allies and help him discover the truth about his parents' mysterious deaths."},
    { title: "Redwall", pages: 351, author: "Brian Jaques", cover: "https://upload.wikimedia.org/wikipedia/en/3/33/RedwallBookCover.jpg", genre: "Fantasy", published: "1986", summary: "As the inhabitants of Redwall Abbey bask in the glorious Summer of the Late Rose, all is quiet and peaceful. But things are not as they seem. Cluny the Scourge—the evil one-eyed rat warlord, is hell-bent on destroying the tranquility as he prepares to fight a bloody battle for the ownership of Redwall. This dazzling story in the Redwall series is packed with all the wit, wisdom, humor, and blood-curdling adventure of the other books in the collection, but has the added bonus of taking the reader right back to the heart and soul of Redwall Abbey and the characters who live there."},
    { title: "Eloquent Ruby", pages: 448, author: "Russ Olsen", cover: "https://images-na.ssl-images-amazon.com/images/I/414gR4dCXiL._SX387_BO1,204,203,200_.jpg", genre: "It’s easy to write correct Ruby code, but to gain the fluency needed to write great Ruby code, you must go beyond syntax and absorb the “Ruby way” of thinking and problem solving. In Eloquent Ruby, Russ Olsen helps you write Ruby like true Rubyists do–so you can leverage its immense, surprising power."},
    { title: "Encyclopedia of Modern Bodybuilding", pages: 800, author: "Arnold Schwarzenegger", cover: "https://www.booktopia.com.au/http_coversbooktopiacomau/600/9780684857213/the-new-encyclopedia-of-modern-bodybuilding.jpg", genre: "Health/Fitness", published: "1985", summary: "The ultimate book on bodybuilding by one of the most popular bodybuilders of all time and the bestselling author of three previous bodybuilding books; covers diet, training, and a history of the sport. Over 850 photographs."},
    { title: "The Book of Sharks", pages: 224, author: "Richard Ellis", cover: "https://images-na.ssl-images-amazon.com/images/I/51F3KSZ4K6L._SX339_BO1,204,203,200_.jpg", genre: "Informational", published: "1976", summary: "Magnificently illustrated and written by the country's foremost painter of marine natural history and subjects, The Book of Sharks is a comprehensive study of the 200 species that populate the oceans of the world. 200 illustrations, 20 in color."},
    { title: "Cat in the Hat", pages: 61, author: "Dr Suess", cover: "https://upload.wikimedia.org/wikipedia/en/b/b5/Seuss-cat-hat.gif", genre: "Children's Literature", published: "1957", summary: "The Cat in the Hat is a children's book written and illustrated by Theodor Geisel under the pen name Dr. Seuss and first published in 1957. The story centers on a tall anthropomorphic cat, who wears a red and white-striped hat and a red bow tie."},
    { title: "Moby-Dick", pages: 378, author: "Herman Melville", cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Moby-Dick_FE_title_page.jpg/330px-Moby-Dick_FE_title_page.jpg", genre: "Novel, Adventure fiction, Epic, Nautical fiction, Encyclopedic novel", published: "1851", summary: "Sailor Ishmael tells the story of the obsessive quest of Ahab, captain of the whaler the Pequod, for revenge on Moby Dick, the white whale that on the previous whaling voyage bit off Ahab's leg at the knee."}
  ]
}
